FPS = 60 
SCREEN_SIZE = WIDTH, HEIGHT = 800 , 600
HORIZONTAL_TILES_AMOUNT = 16
VERTICAL_TILES_AMOUNT = 12
TILES_WIDTH = WIDTH / HORIZONTAL_TILES_AMOUNT
TILES_HEIGHT = HEIGHT / VERTICAL_TILES_AMOUNT

screen_properties = {'SCREEN_SIZE' : SCREEN_SIZE, 
                     'TILES_HEIGHT' : TILES_HEIGHT, 
                     'TILES_WIDTH' : TILES_WIDTH, 
                     'FPS' : FPS}